# Generated by Django 5.2.4 on 2026-03-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_serviceprovider_latitude_serviceprovider_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_category',
            field=models.CharField(max_length=100),
        ),
    ]
